"""Coder Agent - Implements code changes using LangGraph with LLM-powered tools."""

import os
import subprocess
import re
import json
from datetime import datetime
from typing import Dict, Any, List, Optional, Annotated, TypedDict
from agents.base import BaseAgent, AgentState
from prompts import get_prompt
from model import get_llm


class GitNotFoundError(Exception):
    """Raised when Git is not installed or not found in PATH."""
    pass


class CoderAgent(BaseAgent):
    """
    The Coder Agent using LangGraph with LLM-powered code generation:
    1. Creates new git branches
    2. Uses LLM to generate code based on implementation plan
    3. Writes code changes to files
    4. Commits changes with meaningful messages
    """
    
    def __init__(self):
        super().__init__(
            name="Coder",
            description="Implements code changes using LLM-powered generation"
        )
        # Load prompt from file
        self.prompt = get_prompt("coder", default="")
        self.llm = get_llm()
    
    async def execute(self, state: AgentState) -> AgentState:
        """Execute the coding workflow using LLM for code generation."""
        import time
        start_time = time.time()
        
        # Log input
        self.log_input(state)
        self.log("Starting code generation with LLM...", {
            "files_to_modify": state.files_to_modify,
            "implementation_plan": state.implementation_plan.get("summary", "")[:100] if state.implementation_plan else ""
        })
        
        try:
            # Step 1: Create a new branch
            branch_name = self._create_branch(state.repo_path, state.issue)
            state.branch_name = branch_name
            self.log(f"Created branch: {branch_name}")
            
            # Step 2: Get repo context and file contents
            repo_context = self._get_repo_context_from_messages(state)
            file_contents = self._get_file_contents_from_messages(state)
            
            # Step 3: Generate code using LLM for each file
            code_changes = await self._generate_code_with_llm(
                state.issue,
                state.implementation_plan,
                state.files_to_modify,
                repo_context,
                file_contents
            )
            
            state.code_changes = code_changes
            self.log("Code generated by LLM", {"files_generated": list(code_changes.keys())})
            
            # Step 4: Write files to disk
            self._write_files(state.repo_path, code_changes)
            self.log("Files written", {"count": len(code_changes)})
            
            # Step 5: Commit changes
            commit_message = await self._generate_commit_message(state.issue, code_changes)
            self._commit_changes(state.repo_path, commit_message)
            self.log(f"Committed changes: {commit_message}")
            
            state.current_agent = self.name
            state.messages.append({
                "agent": self.name,
                "action": "code_implemented",
                "data": {
                    "branch": branch_name,
                    "files_changed": list(code_changes.keys()),
                    "commit_message": commit_message
                }
            })
            
            # Log output
            duration_ms = (time.time() - start_time) * 1000
            self.log_output(state, duration_ms)
            return state
            
        except Exception as e:
            self.log_error(e, {"files_to_modify": state.files_to_modify})
            state.errors.append(str(e))
            return state
    
    def _get_repo_context_from_messages(self, state: AgentState) -> Dict[str, Any]:
        """Get repo context from RepoReader messages."""
        for msg in state.messages:
            if msg.get("agent") == "RepoReader" and msg.get("action") == "repo_loaded":
                return msg.get("data", {}).get("context_summary", {})
        return {}
    
    def _get_file_contents_from_messages(self, state: AgentState) -> Dict[str, str]:
        """Get file contents from RepoReader messages."""
        for msg in state.messages:
            if msg.get("agent") == "RepoReader" and msg.get("action") == "repo_loaded":
                return msg.get("data", {}).get("file_contents", {})
        return {}
    
    def _create_branch(self, repo_path: str, issue: str) -> str:
        """Create a new git branch for the changes."""
        # Generate branch name from issue
        slug = self._generate_slug(issue)
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        branch_name = f"feature/{slug}-{timestamp}"
        
        if not repo_path or not os.path.exists(repo_path):
            self.log(f"Repo path doesn't exist, using branch name: {branch_name}")
            return branch_name
        
        try:
            # Fetch latest
            subprocess.run(
                ["git", "fetch", "--all"],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Get base branch from env
            base_branch = os.getenv("GITHUB_BASE_BRANCH", "main")
            
            # Checkout base branch
            subprocess.run(
                ["git", "checkout", base_branch],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Pull latest
            subprocess.run(
                ["git", "pull", "origin", base_branch],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Create and checkout new branch
            subprocess.run(
                ["git", "checkout", "-b", branch_name],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            return branch_name
            
        except subprocess.CalledProcessError as e:
            self.log(f"Git branch creation failed: {e}")
            return branch_name
        except FileNotFoundError:
            raise GitNotFoundError("Git is not installed or not found in PATH.")
    
    def _generate_slug(self, issue: str) -> str:
        """Generate a URL-safe slug from the issue text."""
        # Take first 30 characters of issue
        slug = issue[:30].lower()
        # Replace non-alphanumeric with hyphens
        slug = re.sub(r'[^a-z0-9]+', '-', slug)
        # Remove leading/trailing hyphens
        slug = slug.strip('-')
        return slug or "feature"
    
    async def _generate_code_with_llm(
        self,
        issue: str,
        implementation_plan: Dict[str, Any],
        files_to_modify: List[str],
        repo_context: Dict[str, Any],
        existing_file_contents: Dict[str, str]
    ) -> Dict[str, str]:
        """
        Use LLM to generate code for each file based on the implementation plan.
        
        This is the core LLM-powered code generation method.
        """
        code_changes = {}
        
        for file_path in files_to_modify:
            self.log(f"Generating code for: {file_path}")
            
            # Get existing file content if available
            existing_content = existing_file_contents.get(file_path, "")
            
            # Build the prompt for code generation
            prompt = self._build_code_generation_prompt(
                file_path=file_path,
                issue=issue,
                implementation_plan=implementation_plan,
                repo_context=repo_context,
                existing_content=existing_content
            )
            
            # Call LLM to generate code
            try:
                generated_code = await self.llm.generate(
                    prompt=prompt,
                    system_prompt=self.prompt,
                    temperature=0.3  # Lower temperature for more consistent code
                )
                
                # Extract code from response (handle markdown code blocks)
                clean_code = self._extract_code_from_response(generated_code, file_path)
                code_changes[file_path] = clean_code
                
                self.log(f"Successfully generated code for {file_path}", {
                    "code_length": len(clean_code)
                })
                
            except Exception as e:
                self.log(f"LLM code generation failed for {file_path}: {e}")
                # Fallback: create a placeholder file
                code_changes[file_path] = self._create_placeholder_file(file_path, issue)
        
        return code_changes
    
    def _build_code_generation_prompt(
        self,
        file_path: str,
        issue: str,
        implementation_plan: Dict[str, Any],
        repo_context: Dict[str, Any],
        existing_content: str
    ) -> str:
        """Build a comprehensive prompt for code generation."""
        
        # Extract relevant info from implementation plan
        plan_summary = implementation_plan.get("summary", "")
        steps = implementation_plan.get("steps", [])
        dependencies = implementation_plan.get("dependencies", [])
        
        prompt_parts = [
            "Generate complete, production-ready code for the following file.",
            "",
            f"## File to Generate: {file_path}",
            "",
            f"## User Request:",
            issue,
            "",
            f"## Implementation Plan:",
            plan_summary if plan_summary else "Implement the requested functionality.",
            ""
        ]
        
        if steps:
            prompt_parts.append("## Steps to Implement:")
            for i, step in enumerate(steps, 1):
                prompt_parts.append(f"{i}. {step}")
            prompt_parts.append("")
        
        if repo_context:
            prompt_parts.append("## Repository Context:")
            prompt_parts.append(f"- Main Language: {repo_context.get('main_language', 'Python')}")
            prompt_parts.append(f"- Project Type: {repo_context.get('project_type', 'Unknown')}")
            if repo_context.get("frameworks"):
                prompt_parts.append(f"- Frameworks: {', '.join(repo_context.get('frameworks', []))}")
            prompt_parts.append("")
        
        if existing_content:
            prompt_parts.append("## Existing File Content (to modify/extend):")
            prompt_parts.append("```")
            prompt_parts.append(existing_content[:3000])  # Limit to avoid token overflow
            if len(existing_content) > 3000:
                prompt_parts.append("... (truncated)")
            prompt_parts.append("```")
            prompt_parts.append("")
        
        prompt_parts.extend([
            "## Requirements:",
            "1. Generate complete, working code",
            "2. Include proper imports and dependencies",
            "3. Add comprehensive docstrings and comments",
            "4. Include type hints for Python",
            "5. Follow best practices and coding standards",
            "6. Handle errors gracefully",
            "7. Make the code secure (no hardcoded secrets)",
            "",
            "## Output:",
            "Provide ONLY the complete code for the file, no explanations.",
            "Do not wrap in markdown code blocks."
        ])
        
        return "\n".join(prompt_parts)
    
    def _extract_code_from_response(self, response: str, file_path: str) -> str:
        """Extract clean code from LLM response, removing markdown artifacts."""
        code = response.strip()
        
        # Remove markdown code blocks if present
        # Match ```python or ```py or just ```
        patterns = [
            r'^```(?:python|py|javascript|js|typescript|ts|java|go|rust|c|cpp|csharp|cs)?\n?(.*?)```$',
            r'^```\n?(.*?)```$'
        ]
        
        for pattern in patterns:
            match = re.match(pattern, code, re.DOTALL | re.IGNORECASE)
            if match:
                code = match.group(1).strip()
                break
        
        # Remove any leading/trailing quotes
        if code.startswith('"""') and code.endswith('"""'):
            pass  # This is a docstring, keep it
        elif code.startswith('"') and code.endswith('"'):
            code = code[1:-1]
        
        return code
    
    def _create_placeholder_file(self, file_path: str, issue: str) -> str:
        """Create a placeholder file when LLM generation fails."""
        ext = os.path.splitext(file_path)[1]
        
        if ext == ".py":
            return f'''"""
Module: {os.path.basename(file_path)}

Auto-generated placeholder for: {issue[:100]}

TODO: Implement the required functionality.
"""

# Placeholder implementation
def main():
    """Main entry point."""
    pass


if __name__ == "__main__":
    main()
'''
        else:
            return f"// Placeholder for: {issue[:100]}\n// TODO: Implement"
    
    async def _generate_commit_message(self, issue: str, code_changes: Dict[str, str]) -> str:
        """Use LLM to generate a meaningful commit message."""
        files_list = ", ".join(code_changes.keys())
        
        prompt = f"""Generate a concise, descriptive git commit message for the following changes:

User Request: {issue[:200]}

Files Changed: {files_list}

Requirements:
- Start with an action verb (Add, Fix, Update, Implement, Refactor)
- Be concise but descriptive (max 72 characters for first line)
- Follow conventional commit format

Output ONLY the commit message, no explanations."""

        try:
            commit_message = await self.llm.generate(
                prompt=prompt,
                system_prompt="You are a helpful assistant that generates git commit messages.",
                temperature=0.3,
                max_tokens=100
            )
            
            # Clean up the message
            commit_message = commit_message.strip().strip('"').strip("'")
            # Take only the first line
            commit_message = commit_message.split("\n")[0]
            
            return commit_message if commit_message else "Implement requested changes"
            
        except Exception as e:
            self.log(f"Failed to generate commit message: {e}")
            return "Implement requested changes"
    
    def _write_files(self, repo_path: str, code_changes: Dict[str, str]) -> None:
        """Write the generated code to files."""
        for file_path, content in code_changes.items():
            full_path = os.path.join(repo_path, file_path) if repo_path else file_path
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(full_path) if os.path.dirname(full_path) else ".", exist_ok=True)
            
            # Write the file
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            self.log(f"Wrote file: {full_path}")
    
    def _commit_changes(self, repo_path: str, message: str) -> None:
        """Commit the changes to git."""
        if not repo_path or not os.path.exists(repo_path):
            self.log("Skipping git commit - no repo path")
            return
        
        try:
            # Stage all changes
            subprocess.run(
                ["git", "add", "-A"],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            # Commit
            subprocess.run(
                ["git", "commit", "-m", message],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            self.log(f"Committed: {message}")
            
        except subprocess.CalledProcessError as e:
            self.log(f"Git commit failed: {e}")
        except FileNotFoundError:
            raise GitNotFoundError("Git is not installed or not found in PATH.")


# Export
__all__ = ["CoderAgent", "GitNotFoundError"]
