"""Coder Agent - Implements code changes using LangGraph with LLM-powered tools."""

import ast
import os
import subprocess
import re
import json
from datetime import datetime
from typing import Dict, Any, List, Optional
from agents.base import BaseAgent, AgentState
from prompts import get_prompt
from model import get_llm


class GitNotFoundError(Exception):
    """Raised when Git is not installed or not found in PATH."""
    pass


class CoderAgent(BaseAgent):
    """
    The Coder Agent using LangGraph with LLM-powered code generation:
    1. Creates new git branches
    2. Uses LLM to generate code based on implementation plan
    3. Writes code changes to files
    4. Commits changes with meaningful messages
    """
    
    def __init__(self):
        super().__init__(
            name="Coder",
            description="Implements code changes using LLM-powered generation"
        )
        # Load prompt from file
        self.prompt = get_prompt("coder", default="")
        self.llm = get_llm()
    
    async def execute(self, state: AgentState) -> AgentState:
        """Execute the coding workflow using LLM for code generation."""
        import time
        start_time = time.time()
        
        # Log input
        self.log_input(state)
        self.log("Starting code generation with LLM...", {
            "files_to_modify": state.files_to_modify,
            "implementation_plan": state.implementation_plan.get("summary", "")[:100] if state.implementation_plan else ""
        })
        
        try:
            # Step 1: Create a branch only if one doesn't already exist (e.g. review loop-back)
            if not state.branch_name:
                branch_name = self._create_branch(state.repo_path, state.issue)
                state.branch_name = branch_name
                self.log(f"Created branch: {branch_name}")
            else:
                self.log(f"Reusing existing branch: {state.branch_name}")
            
            # Step 2: Use state fields directly (RepoReader writes here); fall back to disk
            repo_context = state.repo_context
            file_contents = state.file_contents or self._read_files_from_disk(
                state.repo_path, state.files_to_modify
            )

            safe_issue = self._sanitize_input(state.issue)

            # Step 3: Generate code using LLM for each file
            code_changes = await self._generate_code_with_llm(
                safe_issue,
                state.implementation_plan,
                state.files_to_modify,
                repo_context,
                file_contents,
                state.last_test_failure,
            )
            
            state.code_changes = code_changes
            self.log("Code generated by LLM", {"files_generated": list(code_changes.keys())})
            
            # Step 4: Write files to disk
            self._write_files(state.repo_path, code_changes)
            self.log("Files written", {"count": len(code_changes)})
            
            # Step 5: Commit changes
            commit_message = await self._generate_commit_message(state.issue, code_changes)
            committed = self._commit_changes(state.repo_path, commit_message)
            if committed:
                self.log(f"Committed changes: {commit_message}")
            else:
                self.log(f"Commit skipped or failed: {commit_message}")
            
            state.current_agent = self.name
            state.messages.append({
                "agent": self.name,
                "action": "code_implemented",
                "data": {
                    "branch": state.branch_name,
                    "files_changed": list(code_changes.keys()),
                    "commit_message": commit_message
                }
            })
            
            # Log output
            duration_ms = (time.time() - start_time) * 1000
            self.log_output(state, duration_ms)
            return state
            
        except Exception as e:
            self.log_error(e, {"files_to_modify": state.files_to_modify})
            state.errors.append(str(e))
            return state
    
    def _validate_python_syntax(self, code: str, file_path: str) -> Optional[str]:
        """Return a SyntaxError description if code is invalid Python, else None."""
        try:
            ast.parse(code)
            return None
        except SyntaxError as exc:
            # Log the problematic line for debugging
            lines = code.split('\n')
            if exc.lineno and exc.lineno <= len(lines):
                problem_line = lines[exc.lineno - 1]
                self.log(f"Syntax error at line {exc.lineno}: {repr(problem_line[:100])}", {"file": file_path})
            return f"SyntaxError in {file_path} at line {exc.lineno}: {exc.msg}"

    def _read_files_from_disk(self, repo_path: str, file_paths: List[str]) -> Dict[str, str]:
        """Read existing file contents from disk (used when RepoReader cache is unavailable)."""
        contents: Dict[str, str] = {}
        if not repo_path:
            return contents
        for rel_path in file_paths:
            full_path = os.path.join(repo_path, rel_path)
            try:
                if os.path.isfile(full_path):
                    with open(full_path, "r", encoding="utf-8", errors="replace") as fh:
                        contents[rel_path] = fh.read()
            except OSError:
                pass
        return contents

    def _create_branch(self, repo_path: str, issue: str) -> str:
        """Create a new git branch for the changes."""
        # Generate branch name from issue
        slug = self._generate_slug(issue)
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        branch_name = f"feature/{slug}-{timestamp}"
        
        if not repo_path or not os.path.exists(repo_path):
            self.log(f"Repo path doesn't exist, using branch name: {branch_name}")
            return branch_name
        
        try:
            # Fetch latest
            subprocess.run(
                ["git", "fetch", "--all"],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Get base branch from env
            base_branch = os.getenv("GITHUB_BASE_BRANCH", "main")
            
            # Checkout base branch
            subprocess.run(
                ["git", "checkout", base_branch],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Pull latest
            subprocess.run(
                ["git", "pull", "origin", base_branch],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Create and checkout new branch
            subprocess.run(
                ["git", "checkout", "-b", branch_name],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            return branch_name
            
        except subprocess.CalledProcessError as e:
            self.log(f"Git branch creation failed: {e}")
            return branch_name
        except FileNotFoundError:
            raise GitNotFoundError("Git is not installed or not found in PATH.")
    
    def _generate_slug(self, issue: str) -> str:
        """Generate a URL-safe slug from the issue text."""
        # Take first 30 characters of issue
        slug = issue[:30].lower()
        # Replace non-alphanumeric with hyphens
        slug = re.sub(r'[^a-z0-9]+', '-', slug)
        # Remove leading/trailing hyphens
        slug = slug.strip('-')
        return slug or "feature"
    
    async def _generate_code_with_llm(
        self,
        issue: str,
        implementation_plan: Dict[str, Any],
        files_to_modify: List[str],
        repo_context: Dict[str, Any],
        existing_file_contents: Dict[str, str],
        last_test_failure: str = "",
    ) -> Dict[str, str]:
        """Generate code for each file; validates Python syntax and retries once on failure."""
        code_changes: Dict[str, str] = {}

        for file_path in files_to_modify:
            self.log(f"Generating code for: {file_path}")
            existing_content = existing_file_contents.get(file_path, "")

            # Include already-generated sibling files so the LLM can match imports/signatures
            already_generated = {k: v for k, v in code_changes.items() if k != file_path}

            prompt = self._build_code_generation_prompt(
                file_path=file_path,
                issue=issue,
                implementation_plan=implementation_plan,
                repo_context=repo_context,
                existing_content=existing_content,
                last_test_failure=last_test_failure,
                already_generated=already_generated,
            )

            try:
                generated_code = await self.llm.generate(
                    prompt=prompt,
                    system_prompt=self.prompt,
                    temperature=0.3,
                )
                clean_code = self._extract_code_from_response(generated_code, file_path)

                # ── Syntax validation (Python only) ───────────────────────────
                if file_path.endswith(".py"):
                    syntax_error = self._validate_python_syntax(clean_code, file_path)
                    if syntax_error:
                        self.log(f"Syntax error on first attempt — retrying: {syntax_error}")
                        retry_prompt = (
                            f"{prompt}\n\n"
                            f"## PREVIOUS ATTEMPT FAILED WITH SYNTAX ERROR\n"
                            f"{syntax_error}\n"
                            f"Fix the error and return the complete corrected file."
                        )
                        generated_code = await self.llm.generate(
                            prompt=retry_prompt,
                            system_prompt=self.prompt,
                            temperature=0.2,
                        )
                        clean_code = self._extract_code_from_response(generated_code, file_path)
                        syntax_error = self._validate_python_syntax(clean_code, file_path)
                        if syntax_error:
                            self.log(f"Syntax still invalid after retry — using placeholder: {syntax_error}")
                            clean_code = self._create_placeholder_file(file_path, issue)

                code_changes[file_path] = clean_code
                self.log(f"Generated {file_path}", {"bytes": len(clean_code)})

            except Exception as exc:
                self.log(f"LLM generation failed for {file_path}: {exc}")
                code_changes[file_path] = self._create_placeholder_file(file_path, issue)

        return code_changes
    
    def _build_code_generation_prompt(
        self,
        file_path: str,
        issue: str,
        implementation_plan: Dict[str, Any],
        repo_context: Dict[str, Any],
        existing_content: str,
        last_test_failure: str = "",
        already_generated: Optional[Dict[str, str]] = None,
    ) -> str:
        """Build a prompt for production-quality code generation."""
        plan_summary = implementation_plan.get("summary", "")
        design_approach = implementation_plan.get("design_approach", "")
        steps = implementation_plan.get("steps", [])
        security_considerations = implementation_plan.get("security_considerations", [])
        error_handling_strategy = implementation_plan.get("error_handling_strategy", "")

        file_plan = ""
        for f in implementation_plan.get("files_to_create", []):
            if isinstance(f, dict) and f.get("path") == file_path:
                file_plan = f"Purpose: {f.get('purpose', '')} | Exports: {', '.join(f.get('exports', []))}"
        if not file_plan:
            for f in implementation_plan.get("files_to_modify", []):
                if isinstance(f, dict) and f.get("path") == file_path:
                    file_plan = f"Current: {f.get('current_state', '')} | Changes: {f.get('changes', '')}"

        main_language = repo_context.get("main_language", "Python")
        frameworks = ", ".join(repo_context.get("frameworks", [])) or "None detected"

        prompt_parts = [
            "You are Jordan, Senior Software Engineer in the Implementation phase of the SDLC.",
            "Write production-ready code as if a tired senior engineer will maintain it at 2 AM.",
            "Make it obvious, safe, and correct. Follow the plan precisely — no gold-plating.",
            "",
            f"## File: {file_path}",
            f"## Plan for this file: {file_plan}" if file_plan else "",
            "",
            "## User Request:",
            issue,
            "",
            "## Implementation Plan:",
            plan_summary if plan_summary else "Implement the requested functionality.",
        ]

        if design_approach:
            prompt_parts.extend(["", f"## Design Approach: {design_approach}"])

        if steps:
            prompt_parts.extend(["", "## Implementation Steps (follow in order):"])
            for i, step in enumerate(steps, 1):
                if isinstance(step, dict):
                    step_text = f"{step.get('action', '')}: {step.get('description', '')}".strip(": ")
                    prompt_parts.append(f"{i}. {step_text}")
                else:
                    prompt_parts.append(f"{i}. {step}")

        prompt_parts.extend([
            "",
            "## Repository Context:",
            f"- Language: {main_language}",
            f"- Project Type: {repo_context.get('project_type', 'Unknown')}",
            f"- Frameworks: {frameworks}",
            "",
        ])

        if existing_content:
            prompt_parts.extend([
                "## Existing File (match its style exactly — naming, imports, patterns):",
                "```",
                existing_content[:3000],
                *( ["... (truncated)"] if len(existing_content) > 3000 else [] ),
                "```",
                "",
            ])

        # Cross-file consistency: show already-generated siblings so imports stay aligned
        if already_generated:
            prompt_parts.append("## Other Files Already Generated (match imports and signatures):")
            for sibling_path, sibling_code in list(already_generated.items())[:2]:
                prompt_parts.extend([
                    f"### {sibling_path}:",
                    "```",
                    sibling_code[:800],
                    *( ["... (truncated)"] if len(sibling_code) > 800 else [] ),
                    "```",
                ])
            prompt_parts.append("")

        # Feed test failure details so the Coder knows exactly what broke
        if last_test_failure:
            prompt_parts.extend([
                "## PREVIOUS TEST RUN FAILED — FIX THESE FAILURES:",
                "```",
                last_test_failure[:3000],
                *( ["... (truncated)"] if len(last_test_failure) > 3000 else [] ),
                "```",
                "Your code must make these tests pass. Do not change the tests.",
                "",
            ])

        if security_considerations:
            prompt_parts.extend([
                "## Security Requirements (non-negotiable):",
                *[f"- {s}" for s in security_considerations],
                "",
            ])

        if error_handling_strategy:
            prompt_parts.extend([f"## Error Handling Strategy: {error_handling_strategy}", ""])

        prompt_parts.extend([
            "## Mandatory Code Standards:",
            "SECURITY: never hardcode secrets; bcrypt/argon2 for passwords; parameterised SQL; validate all inputs.",
            "QUALITY: type hints on all signatures; specific exception types; structured logging with context.",
            "",
            "## Output:",
            "Provide ONLY the complete file code.",
            "No === FILE: === headers. No markdown fencing. No explanations. Just the raw source code.",
        ])

        return "\n".join(p for p in prompt_parts if p is not None)
    
    def _extract_code_from_response(self, response: str, file_path: str) -> str:
        """Extract clean code from LLM response, removing markdown artifacts."""
        code = response.strip()

        # Log raw response for debugging
        preview = repr(code[:300]) if len(code) > 300 else repr(code)
        self.log(f"Raw LLM response preview: {preview}", {"file": file_path})

        # 0. Strip === FILE: filename === headers produced by multi-file LLM responses.
        #    The model sometimes wraps each file in "=== FILE: path ===\n<code>\n=== FILE: ...".
        #    We want only the block that belongs to the requested file, or the first block if
        #    no filename match is found.
        file_header_re = re.compile(r'^===\s*FILE:[^\n]*===\s*\n', re.MULTILINE)
        if file_header_re.search(code):
            # Try to find a block whose header contains this file's name
            escaped = re.escape(os.path.basename(file_path))
            named_block = re.search(
                rf'===\s*FILE:[^\n]*{escaped}[^\n]*===\s*\n(.*?)(?:(?:===\s*FILE:)|\Z)',
                code,
                re.DOTALL | re.IGNORECASE,
            )
            if named_block:
                code = named_block.group(1).strip()
                self.log(f"Extracted named file block for {file_path}")
            else:
                # Fall back to the content after the first header
                first_header = file_header_re.search(code)
                code = code[first_header.end():]
                next_header = file_header_re.search(code)
                if next_header:
                    code = code[:next_header.start()]
                code = code.strip()
                self.log(f"Stripped === FILE: === header (no name match)", {"file": file_path})

        # 1. Extract from markdown code blocks (most reliable, LLMs understand this well)
        code_block_match = re.search(
            r'```(?:python|py)?\s*\n(.*?)```',
            code,
            re.DOTALL | re.IGNORECASE
        )
        if code_block_match:
            extracted = code_block_match.group(1).strip()
            self.log(f"Extracted from markdown code block", {"length": len(extracted)})
            return extracted
        
        # 2. Try full-response patterns (response is entirely a code block)
        patterns = [
            r'^```(?:python|py|javascript|js|typescript|ts|java|go|rust|c|cpp|csharp|cs)?\s*\n?(.*?)```\s*$',
            r'^```\s*\n?(.*?)```\s*$'
        ]
        
        for pattern in patterns:
            match = re.match(pattern, code, re.DOTALL | re.IGNORECASE)
            if match:
                extracted = match.group(1).strip()
                self.log(f"Extracted from full code block", {"length": len(extracted)})
                return extracted
        
        # 3. No code block found - clean up raw response
        self.log(f"No code block found, cleaning raw response", {"length": len(code)})
        
        # Remove common preamble text
        preamble_patterns = [
            r"^Here(?:'s| is) the (?:complete |updated |fixed )?(?:code|file|implementation)[:\s]*\n+",
            r"^Below is the (?:complete |updated )?(?:code|file)[:\s]*\n+",
            r"^(?:Sure|Certainly|Of course)[,!]?\s*(?:here(?:'s| is))?[:\s]*\n+",
        ]
        for pattern in preamble_patterns:
            code = re.sub(pattern, "", code, flags=re.IGNORECASE)
        
        # Remove trailing explanations
        code = re.sub(r"\n\n(?:This (?:code|implementation)|Note:|Explanation:).*$", "", code, flags=re.DOTALL | re.IGNORECASE)
        
        # Remove any leading/trailing quotes
        if code.startswith('"') and code.endswith('"') and not code.startswith('"""'):
            code = code[1:-1]
        
        return code.strip()
    
    def _create_placeholder_file(self, file_path: str, issue: str) -> str:
        """Create a placeholder file when LLM generation fails."""
        ext = os.path.splitext(file_path)[1]
        
        if ext == ".py":
            return f'''"""
Module: {os.path.basename(file_path)}

Auto-generated placeholder for: {issue[:100]}

TODO: Implement the required functionality.
"""

# Placeholder implementation
def main():
    """Main entry point."""
    pass


if __name__ == "__main__":
    main()
'''
        else:
            return f"// Placeholder for: {issue[:100]}\n// TODO: Implement"
    
    async def _generate_commit_message(self, issue: str, code_changes: Dict[str, str]) -> str:
        """Use LLM to generate a meaningful commit message."""
        files_list = ", ".join(code_changes.keys())
        
        prompt = f"""Generate a concise, descriptive git commit message for the following changes:

User Request: {issue[:200]}

Files Changed: {files_list}

Requirements:
- Start with an action verb (Add, Fix, Update, Implement, Refactor)
- Be concise but descriptive (max 72 characters for first line)
- Follow conventional commit format

Output ONLY the commit message, no explanations."""

        try:
            commit_message = await self.llm.generate(
                prompt=prompt,
                system_prompt="You are a helpful assistant that generates git commit messages.",
                temperature=0.3,
                max_tokens=1000  # reasoning models consume tokens before producing output
            )
            
            # Clean up the message
            commit_message = commit_message.strip().strip('"').strip("'")
            # Take only the first line
            commit_message = commit_message.split("\n")[0]
            
            return commit_message if commit_message else "Implement requested changes"
            
        except Exception as e:
            self.log(f"Failed to generate commit message: {e}")
            return "Implement requested changes"
    
    def _write_files(self, repo_path: str, code_changes: Dict[str, str]) -> None:
        """Write the generated code to files."""
        for file_path, content in code_changes.items():
            full_path = os.path.join(repo_path, file_path) if repo_path else file_path
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(full_path) if os.path.dirname(full_path) else ".", exist_ok=True)
            
            # Write the file
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            self.log(f"Wrote file: {full_path}")
    
    def _commit_changes(self, repo_path: str, message: str) -> bool:
        """Commit the changes to git. Returns True on success, False on failure."""
        if not repo_path or not os.path.exists(repo_path):
            self.log("Skipping git commit - no repo path")
            return False

        try:
            subprocess.run(
                ["git", "add", "-A"],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            subprocess.run(
                ["git", "commit", "-m", message],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            self.log(f"Committed: {message}")
            return True

        except subprocess.CalledProcessError as e:
            self.log(f"Git commit failed: {e}")
            return False
        except FileNotFoundError:
            raise GitNotFoundError("Git is not installed or not found in PATH.")


# Export
__all__ = ["CoderAgent", "GitNotFoundError"]
