"""Stub FastAPI server for EverAssist UI.

Provides dummy endpoints that the frontend can call while the real backend
is under development.

Run locally:
    cd backend/stub-ui
    pip install -r requirements.txt
    uvicorn main:app --reload --port 8001
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

app = FastAPI(title="EverAssist Stub UI API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class AttachmentIn(BaseModel):
    name: str
    size: Optional[str] = None


class RequirementForm(BaseModel):
    title: str
    lob: str = Field(default="", description="Line of Business")
    priority: str = ""
    target_date: str = ""
    stakeholders: str = ""
    goal: str = ""
    acceptance_criteria: List[str] = []
    additional_requirements: List[str] = []
    attachments: List[AttachmentIn] = []


class GenerateMdResponse(BaseModel):
    markdown: str
    generated_at: str
    requirement_id: str


class SubmitResponse(BaseModel):
    status: str
    requirement_id: str
    message: str


def _build_markdown(form: RequirementForm, requirement_id: str) -> str:
    lines: List[str] = []
    lines.append(f"# {form.title or 'Untitled Requirement'}")
    lines.append("")
    lines.append(f"**ID:** `{requirement_id}`  ")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).isoformat()}")
    lines.append("")
    lines.append("## Overview")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Line of Business | {form.lob or '—'} |")
    lines.append(f"| Priority | {form.priority or '—'} |")
    lines.append(f"| Target Date | {form.target_date or '—'} |")
    lines.append(f"| Stakeholders | {form.stakeholders or '—'} |")
    lines.append("")
    lines.append("## Business Goal")
    lines.append("")
    lines.append(form.goal or "_No goal provided._")
    lines.append("")
    lines.append("## Acceptance Criteria")
    lines.append("")
    if form.acceptance_criteria:
        for item in form.acceptance_criteria:
            lines.append(f"- [ ] {item}")
    else:
        lines.append("_None specified._")
    lines.append("")
    lines.append("## Additional Requirements")
    lines.append("")
    if form.additional_requirements:
        for item in form.additional_requirements:
            lines.append(f"- {item}")
    else:
        lines.append("_None specified._")
    lines.append("")
    lines.append("## Attachments")
    lines.append("")
    if form.attachments:
        for att in form.attachments:
            size = f" ({att.size})" if att.size else ""
            lines.append(f"- `{att.name}`{size}")
    else:
        lines.append("_No files attached._")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by EverAssist Stub UI API_")
    return "\n".join(lines)


@app.get("/api/health")
def health():
    return {"status": "ok", "service": "everassist-stub-ui"}


@app.post("/api/requirements/generate-md", response_model=GenerateMdResponse)
def generate_md(form: RequirementForm) -> GenerateMdResponse:
    requirement_id = f"US-{abs(hash(form.title)) % 900 + 100}"
    markdown = _build_markdown(form, requirement_id)
    return GenerateMdResponse(
        markdown=markdown,
        generated_at=datetime.now(timezone.utc).isoformat(),
        requirement_id=requirement_id,
    )


@app.post("/api/requirements/submit", response_model=SubmitResponse)
def submit_requirement(form: RequirementForm) -> SubmitResponse:
    requirement_id = f"US-{abs(hash(form.title)) % 900 + 100}"
    return SubmitResponse(
        status="accepted",
        requirement_id=requirement_id,
        message=f"Requirement '{form.title}' submitted to the pipeline.",
    )
