/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequirementIdRouteImport } from './routes/requirement.$id'
import { Route as PolicyNewRouteImport } from './routes/policy.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementIdRoute = RequirementIdRouteImport.update({
  id: '/requirement/$id',
  path: '/requirement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyNewRoute = PolicyNewRouteImport.update({
  id: '/policy/new',
  path: '/policy/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policy/new': typeof PolicyNewRoute
  '/requirement/$id': typeof RequirementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policy/new': typeof PolicyNewRoute
  '/requirement/$id': typeof RequirementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policy/new': typeof PolicyNewRoute
  '/requirement/$id': typeof RequirementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/policy/new' | '/requirement/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/policy/new' | '/requirement/$id'
  id: '__root__' | '/' | '/policy/new' | '/requirement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolicyNewRoute: typeof PolicyNewRoute
  RequirementIdRoute: typeof RequirementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirement/$id': {
      id: '/requirement/$id'
      path: '/requirement/$id'
      fullPath: '/requirement/$id'
      preLoaderRoute: typeof RequirementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/new': {
      id: '/policy/new'
      path: '/policy/new'
      fullPath: '/policy/new'
      preLoaderRoute: typeof PolicyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolicyNewRoute: PolicyNewRoute,
  RequirementIdRoute: RequirementIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
