"""Coder Agent - Implements code changes using LangGraph with LLM-powered tools."""

import os
import subprocess
import re
import json
import glob as glob_module
from datetime import datetime
from typing import Dict, Any, List, Optional
from agents.base import BaseAgent, AgentState
from prompts import get_prompt
from model import get_llm


class GitNotFoundError(Exception):
    """Raised when Git is not installed or not found in PATH."""
    pass


class CoderAgent(BaseAgent):
    """
    The Coder Agent using LangGraph with LLM-powered code generation:
    1. Creates new git branches
    2. Uses LLM to generate code based on implementation plan
    3. Writes code changes to files
    4. Commits changes with meaningful messages
    """
    
    def __init__(self):
        super().__init__(
            name="Coder",
            description="Implements code changes using LLM-powered generation"
        )
        # Load prompt from file
        self.prompt = get_prompt("coder", default="")
        self.llm = get_llm()
    
    async def execute(self, state: AgentState) -> AgentState:
        """Execute the coding workflow using LLM for code generation."""
        import time
        start_time = time.time()
        
        # Log input
        self.log_input(state)
        
        # Check if this is a retry due to test failures
        test_failure_info = self._get_test_failure_info(state)
        is_test_failure_retry = test_failure_info["has_failures"] and state.test_iteration > 0
        
        if is_test_failure_retry:
            self.log("Retrying code generation to fix test failures...", {
                "test_iteration": state.test_iteration,
                "files_to_modify": state.files_to_modify,
                "test_output_preview": test_failure_info["output"][:200] if test_failure_info["output"] else ""
            })
        else:
            self.log("Starting code generation with LLM...", {
                "files_to_modify": state.files_to_modify,
                "implementation_plan": state.implementation_plan.get("summary", "")[:100] if state.implementation_plan else ""
            })
        
        try:
            # Step 1: Create a branch only if one doesn't already exist (e.g. review loop-back)
            if not state.branch_name:
                branch_name = self._create_branch(state.repo_path, state.issue)
                state.branch_name = branch_name
                self.log(f"Created branch: {branch_name}")
            else:
                self.log(f"Reusing existing branch: {state.branch_name}")
            
            # Step 2: Get repo context and file contents
            repo_context = self._get_repo_context_from_messages(state)
            file_contents = self._get_file_contents_from_messages(state)
            
            # Step 2.5: Expand glob patterns and validate file paths
            validated_files = self._expand_and_validate_file_paths(
                state.repo_path,
                state.files_to_modify,
                file_contents
            )
            self.log(f"Validated file paths", {
                "original_count": len(state.files_to_modify),
                "validated_count": len(validated_files),
                "files": validated_files
            })
            
            # Step 3: Generate code using LLM for each file
            code_changes = await self._generate_code_with_llm(
                state.issue,
                state.implementation_plan,
                validated_files,  # Use validated files instead of state.files_to_modify
                repo_context,
                file_contents,
                test_failure_info=test_failure_info if is_test_failure_retry else None,
                review_findings=state.review_findings if state.review_findings else None
            )
            
            state.code_changes = code_changes
            self.log("Code generated by LLM", {"files_generated": list(code_changes.keys())})
            
            # Step 4: Write files to disk
            self._write_files(state.repo_path, code_changes)
            self.log("Files written", {"count": len(code_changes)})
            
            # Step 5: Commit changes
            commit_message = await self._generate_commit_message(state.issue, code_changes)
            self._commit_changes(state.repo_path, commit_message)
            self.log(f"Committed changes: {commit_message}")
            
            state.current_agent = self.name
            state.messages.append({
                "agent": self.name,
                "action": "code_implemented",
                "data": {
                    "branch": state.branch_name,
                    "files_changed": list(code_changes.keys()),
                    "commit_message": commit_message
                }
            })
            
            # Log output
            duration_ms = (time.time() - start_time) * 1000
            self.log_output(state, duration_ms)
            return state
            
        except Exception as e:
            self.log_error(e, {"files_to_modify": state.files_to_modify})
            state.errors.append(str(e))
            return state
    
    def _get_repo_context_from_messages(self, state: AgentState) -> Dict[str, Any]:
        """Get repo context from RepoReader messages."""
        for msg in state.messages:
            if msg.get("agent") == "RepoReader" and msg.get("action") == "repo_loaded":
                return msg.get("data", {}).get("context_summary", {})
        return {}
    
    def _get_file_contents_from_messages(self, state: AgentState) -> Dict[str, str]:
        """Get file contents from RepoReader messages."""
        for msg in state.messages:
            if msg.get("agent") == "RepoReader" and msg.get("action") == "repo_loaded":
                return msg.get("data", {}).get("file_contents", {})
        return {}
    
    def _expand_and_validate_file_paths(self, repo_path: str, files_to_modify: List[str], existing_file_contents: Dict[str, str]) -> List[str]:
        """
        Expand glob patterns and filter out invalid file paths.
        
        - Expands patterns like '*.cs' or 'Controllers/*.cs' to actual files
        - Skips patterns that don't match any files (for new file creation, don't use globs)
        - Returns a list of valid, concrete file paths
        """
        expanded_files = []
        
        for file_path in files_to_modify:
            # Check if path contains glob characters
            if '*' in file_path or '?' in file_path or '[' in file_path:
                # This is a glob pattern - expand it
                if repo_path and os.path.exists(repo_path):
                    full_pattern = os.path.join(repo_path, file_path)
                    matched_files = glob_module.glob(full_pattern, recursive=True)
                    
                    if matched_files:
                        # Convert back to relative paths
                        for matched in matched_files:
                            rel_path = os.path.relpath(matched, repo_path)
                            # Normalize path separators
                            rel_path = rel_path.replace('\\', '/')
                            expanded_files.append(rel_path)
                            self.log(f"Expanded glob '{file_path}' to: {rel_path}")
                    else:
                        self.log(f"Skipping glob pattern '{file_path}' - no matching files found")
                else:
                    # No repo path - check if pattern matches any files in existing_file_contents
                    import fnmatch
                    matched = [f for f in existing_file_contents.keys() if fnmatch.fnmatch(f, file_path)]
                    if matched:
                        expanded_files.extend(matched)
                        self.log(f"Expanded glob '{file_path}' using file contents: {matched}")
                    else:
                        self.log(f"Skipping glob pattern '{file_path}' - cannot expand without repo context")
            else:
                # Regular file path - add as-is
                expanded_files.append(file_path)
        
        # Remove duplicates while preserving order
        seen = set()
        unique_files = []
        for f in expanded_files:
            if f not in seen:
                seen.add(f)
                unique_files.append(f)
        
        return unique_files

    def _get_test_failure_info(self, state: AgentState) -> Dict[str, Any]:
        """Extract test failure information from state if tests have failed."""
        test_info = {
            "has_failures": False,
            "iteration": state.test_iteration,
            "output": "",
            "failed_tests": [],
            "error_messages": []
        }
        
        test_results = state.test_results
        if not test_results:
            return test_info
        
        if test_results.get("status") == "failed":
            test_info["has_failures"] = True
            test_info["output"] = test_results.get("output", "")[:5000]  # Limit output size
            test_info["failed_tests"] = test_results.get("failed_tests", [])
            test_info["error_messages"] = test_results.get("errors", [])
        
        return test_info
    
    def _get_review_findings_for_file(self, state: AgentState, file_path: str) -> List[Dict[str, Any]]:
        """Get review findings specific to a file."""
        findings = []
        for finding in state.review_findings:
            if finding.get("file") == file_path or finding.get("path") == file_path:
                findings.append(finding)
        return findings
    
    def _create_branch(self, repo_path: str, issue: str) -> str:
        """Create a new git branch for the changes."""
        # Generate branch name from issue
        slug = self._generate_slug(issue)
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        branch_name = f"feature/{slug}-{timestamp}"
        
        if not repo_path or not os.path.exists(repo_path):
            self.log(f"Repo path doesn't exist, using branch name: {branch_name}")
            return branch_name
        
        try:
            # Fetch latest
            subprocess.run(
                ["git", "fetch", "--all"],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Get base branch from env
            base_branch = os.getenv("GITHUB_BASE_BRANCH", "main")
            
            # Checkout base branch
            subprocess.run(
                ["git", "checkout", base_branch],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Pull latest
            subprocess.run(
                ["git", "pull", "origin", base_branch],
                cwd=repo_path,
                capture_output=True,
                check=False
            )
            
            # Create and checkout new branch
            subprocess.run(
                ["git", "checkout", "-b", branch_name],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            return branch_name
            
        except subprocess.CalledProcessError as e:
            self.log(f"Git branch creation failed: {e}")
            return branch_name
        except FileNotFoundError:
            raise GitNotFoundError("Git is not installed or not found in PATH.")
    
    def _generate_slug(self, issue: str) -> str:
        """Generate a URL-safe slug from the issue text."""
        # Take first 30 characters of issue
        slug = issue[:30].lower()
        # Replace non-alphanumeric with hyphens
        slug = re.sub(r'[^a-z0-9]+', '-', slug)
        # Remove leading/trailing hyphens
        slug = slug.strip('-')
        return slug or "feature"
    
    async def _generate_code_with_llm(
        self,
        issue: str,
        implementation_plan: Dict[str, Any],
        files_to_modify: List[str],
        repo_context: Dict[str, Any],
        existing_file_contents: Dict[str, str],
        test_failure_info: Optional[Dict[str, Any]] = None,
        review_findings: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, str]:
        """
        Use LLM to generate code for each file based on the implementation plan.
        
        This is the core LLM-powered code generation method.
        When test_failure_info is provided, focuses on fixing test failures.
        """
        code_changes = {}
        
        for file_path in files_to_modify:
            if test_failure_info and test_failure_info.get("has_failures"):
                self.log(f"Fixing code for: {file_path} (test failure retry)")
            else:
                self.log(f"Generating code for: {file_path}")
            
            # Get existing file content if available
            existing_content = existing_file_contents.get(file_path, "")
            
            # Get file-specific review findings
            file_review_findings = []
            if review_findings:
                for finding in review_findings:
                    if finding.get("file") == file_path or finding.get("path") == file_path:
                        file_review_findings.append(finding)
            
            # Build the prompt for code generation
            prompt = self._build_code_generation_prompt(
                file_path=file_path,
                issue=issue,
                implementation_plan=implementation_plan,
                repo_context=repo_context,
                existing_content=existing_content,
                test_failure_info=test_failure_info,
                review_findings=file_review_findings
            )
            
            # Call LLM to generate code
            try:
                generated_code = await self.llm.generate(
                    prompt=prompt,
                    system_prompt=self.prompt,
                    temperature=0.3  # Lower temperature for more consistent code
                )
                
                # Extract code from response (handle markdown code blocks)
                clean_code = self._extract_code_from_response(generated_code, file_path)
                code_changes[file_path] = clean_code
                
                self.log(f"Successfully generated code for {file_path}", {
                    "code_length": len(clean_code)
                })
                
            except Exception as e:
                self.log(f"LLM code generation failed for {file_path}: {e}")
                # Fallback: create a placeholder file
                code_changes[file_path] = self._create_placeholder_file(file_path, issue)
        
        return code_changes
    
    def _build_code_generation_prompt(
        self,
        file_path: str,
        issue: str,
        implementation_plan: Dict[str, Any],
        repo_context: Dict[str, Any],
        existing_content: str,
        test_failure_info: Optional[Dict[str, Any]] = None,
        review_findings: Optional[List[Dict[str, Any]]] = None
    ) -> str:
        """Build a comprehensive SDLC-aware prompt for production-quality code generation.
        
        When test_failure_info is provided, includes test failure context to help fix issues.
        When review_findings is provided, includes reviewer feedback for the file.
        """

        plan_summary = implementation_plan.get("summary", "")
        design_approach = implementation_plan.get("design_approach", "")
        steps = implementation_plan.get("steps", [])
        security_considerations = implementation_plan.get("security_considerations", [])
        error_handling_strategy = implementation_plan.get("error_handling_strategy", "")

        # Find the file-specific plan entry
        file_plan = ""
        for f in implementation_plan.get("files_to_create", []):
            if isinstance(f, dict) and f.get("path") == file_path:
                file_plan = f"Purpose: {f.get('purpose', '')} | Exports: {', '.join(f.get('exports', []))}"
        if not file_plan:
            for f in implementation_plan.get("files_to_modify", []):
                if isinstance(f, dict) and f.get("path") == file_path:
                    file_plan = f"Current: {f.get('current_state', '')} | Changes: {f.get('changes', '')}"

        main_language = repo_context.get("main_language", "Python")
        frameworks = ", ".join(repo_context.get("frameworks", [])) or "None detected"

        prompt_parts = [
            "You are Jordan, Senior Software Engineer in the Implementation phase of the SDLC.",
            "Write production-ready code as if a tired senior engineer will maintain it at 2 AM during an incident.",
            "Make it obvious, safe, and correct. Follow the plan precisely — no gold-plating.",
            "",
            f"## File: {file_path}",
            f"## Plan for this file: {file_plan}" if file_plan else "",
            "",
            "## User Request:",
            issue,
            "",
            "## Implementation Plan:",
            plan_summary if plan_summary else "Implement the requested functionality.",
        ]

        if design_approach:
            prompt_parts.extend(["", f"## Design Approach: {design_approach}"])

        if steps:
            prompt_parts.extend(["", "## Implementation Steps (follow in order):"])
            for i, step in enumerate(steps, 1):
                if isinstance(step, dict):
                    action = step.get("action", "")
                    desc = step.get("description", "")
                    step_text = f"{action}: {desc}".strip(": ")
                    prompt_parts.append(f"{i}. {step_text}")
                else:
                    prompt_parts.append(f"{i}. {step}")

        prompt_parts.extend([
            "",
            "## Repository Context:",
            f"- Language: {main_language}",
            f"- Project Type: {repo_context.get('project_type', 'Unknown')}",
            f"- Frameworks: {frameworks}",
            "",
        ])

        if existing_content:
            prompt_parts.extend([
                "## Existing File (match its style exactly — naming, imports, patterns):",
                "```",
                existing_content[:3000],
                *( ["... (truncated)"] if len(existing_content) > 3000 else [] ),
                "```",
                "",
            ])

        if security_considerations:
            prompt_parts.extend([
                "## Security Requirements (non-negotiable):",
                *[f"- {s}" for s in security_considerations],
                "",
            ])

        if error_handling_strategy:
            prompt_parts.extend([
                f"## Error Handling Strategy: {error_handling_strategy}",
                "",
            ])

        # Add test failure context if this is a retry
        if test_failure_info and test_failure_info.get("has_failures"):
            prompt_parts.extend([
                "## ⚠️ CRITICAL: TEST FAILURES TO FIX (iteration {})".format(test_failure_info.get("iteration", 1)),
                "The previous code failed tests. You MUST fix these specific issues:",
                "",
            ])
            
            test_output = test_failure_info.get("output", "")
            if test_output:
                prompt_parts.extend([
                    "### Test Output (errors to fix):",
                    "```",
                    test_output[:3000],
                    "```" if len(test_output) <= 3000 else "... (truncated)\n```",
                    "",
                ])
            
            failed_tests = test_failure_info.get("failed_tests", [])
            if failed_tests:
                prompt_parts.extend([
                    "### Failed Test Cases:",
                    *[f"- {t}" for t in failed_tests[:20]],
                    "",
                ])
            
            error_messages = test_failure_info.get("error_messages", [])
            if error_messages:
                prompt_parts.extend([
                    "### Error Messages:",
                    *[f"- {e}" for e in error_messages[:10]],
                    "",
                ])
            
            prompt_parts.extend([
                "IMPORTANT: Analyze the test failures above and fix the code accordingly.",
                "Focus on the specific errors — do not rewrite everything, just fix what's broken.",
                "",
            ])
        
        # Add review findings if available
        if review_findings and len(review_findings) > 0:
            prompt_parts.extend([
                "## Code Review Findings to Address:",
            ])
            for finding in review_findings[:10]:  # Limit to 10 findings
                severity = finding.get("severity", "info")
                message = finding.get("message", finding.get("description", ""))
                line = finding.get("line", "")
                line_info = f" (line {line})" if line else ""
                prompt_parts.append(f"- [{severity.upper()}]{line_info}: {message}")
            prompt_parts.append("")

        prompt_parts.extend([
            "## Mandatory Code Standards:",
            "SECURITY (non-negotiable):",
            "  - NEVER hardcode passwords, API keys, tokens — use os.getenv()",
            "  - Hash passwords with bcrypt or argon2id — never MD5, SHA1, or plaintext",
            "  - Use parameterised queries for ALL database operations — no string-concatenated SQL",
            "  - Validate and sanitise ALL user inputs before any operation",
            "  - Add auth/permission checks before every data access operation",
            "",
            "CODE QUALITY:",
            "  - Type hints on ALL function signatures (parameters AND return type)",
            "  - Docstrings on all public classes and methods (Google style)",
            "  - Catch specific exception types — never bare `except:`",
            "  - Log errors with context before re-raising: include user_id, request_id, file path",
            "  - Use f-strings for formatting; avoid % and .format()",
            "  - Prefer dataclasses or Pydantic models over plain dicts for structured data",
            "",
            "OBSERVABILITY:",
            "  - Log at INFO for business events, ERROR for failures, DEBUG for dev details",
            "  - Include contextual info in every log line (user_id, file, operation)",
            "",
            "## Output:",
            "Provide ONLY the complete file code. No explanations. No markdown fencing.",
        ])

        return "\n".join(p for p in prompt_parts if p is not None)
    
    def _extract_code_from_response(self, response: str, file_path: str) -> str:
        """Extract clean code from LLM response, removing markdown artifacts."""
        code = response.strip()
        
        # Remove markdown code blocks if present
        # Match ```python or ```py or just ```
        patterns = [
            r'^```(?:python|py|javascript|js|typescript|ts|java|go|rust|c|cpp|csharp|cs)?\n?(.*?)```$',
            r'^```\n?(.*?)```$'
        ]
        
        for pattern in patterns:
            match = re.match(pattern, code, re.DOTALL | re.IGNORECASE)
            if match:
                code = match.group(1).strip()
                break
        
        # Remove any leading/trailing quotes
        if code.startswith('"""') and code.endswith('"""'):
            pass  # This is a docstring, keep it
        elif code.startswith('"') and code.endswith('"'):
            code = code[1:-1]
        
        return code
    
    def _create_placeholder_file(self, file_path: str, issue: str) -> str:
        """Create a placeholder file when LLM generation fails."""
        ext = os.path.splitext(file_path)[1]
        
        if ext == ".py":
            return f'''"""
Module: {os.path.basename(file_path)}

Auto-generated placeholder for: {issue[:100]}

TODO: Implement the required functionality.
"""

# Placeholder implementation
def main():
    """Main entry point."""
    pass


if __name__ == "__main__":
    main()
'''
        else:
            return f"// Placeholder for: {issue[:100]}\n// TODO: Implement"
    
    async def _generate_commit_message(self, issue: str, code_changes: Dict[str, str]) -> str:
        """Use LLM to generate a meaningful commit message."""
        files_list = ", ".join(code_changes.keys())
        
        prompt = f"""Generate a concise, descriptive git commit message for the following changes:

User Request: {issue[:200]}

Files Changed: {files_list}

Requirements:
- Start with an action verb (Add, Fix, Update, Implement, Refactor)
- Be concise but descriptive (max 72 characters for first line)
- Follow conventional commit format

Output ONLY the commit message, no explanations."""

        try:
            commit_message = await self.llm.generate(
                prompt=prompt,
                system_prompt="You are a helpful assistant that generates git commit messages.",
                temperature=0.3,
                max_tokens=100
            )
            
            # Clean up the message
            commit_message = commit_message.strip().strip('"').strip("'")
            # Take only the first line
            commit_message = commit_message.split("\n")[0]
            
            return commit_message if commit_message else "Implement requested changes"
            
        except Exception as e:
            self.log(f"Failed to generate commit message: {e}")
            return "Implement requested changes"
    
    def _write_files(self, repo_path: str, code_changes: Dict[str, str]) -> None:
        """Write the generated code to files."""
        for file_path, content in code_changes.items():
            full_path = os.path.join(repo_path, file_path) if repo_path else file_path
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(full_path) if os.path.dirname(full_path) else ".", exist_ok=True)
            
            # Write the file
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            self.log(f"Wrote file: {full_path}")
    
    def _commit_changes(self, repo_path: str, message: str) -> None:
        """Commit the changes to git."""
        if not repo_path or not os.path.exists(repo_path):
            self.log("Skipping git commit - no repo path")
            return
        
        try:
            # Stage all changes
            subprocess.run(
                ["git", "add", "-A"],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            # Commit
            subprocess.run(
                ["git", "commit", "-m", message],
                cwd=repo_path,
                capture_output=True,
                check=True
            )
            
            self.log(f"Committed: {message}")
            
        except subprocess.CalledProcessError as e:
            self.log(f"Git commit failed: {e}")
        except FileNotFoundError:
            raise GitNotFoundError("Git is not installed or not found in PATH.")


# Export
__all__ = ["CoderAgent", "GitNotFoundError"]
